// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP8pn5wR-tXM5fTe2eBAb-EJqjxBCZrno',
    appId: '1:751087584610:web:4c56374a13600bebb3d83b',
    messagingSenderId: '751087584610',
    projectId: 'petguardpro-efda9',
    authDomain: 'petguardpro-efda9.firebaseapp.com',
    storageBucket: 'petguardpro-efda9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9aQwPWGus0Zc-pgPqRK2yBWUEM9ed3M',
    appId: '1:751087584610:android:fd9cdde9566979fab3d83b',
    messagingSenderId: '751087584610',
    projectId: 'petguardpro-efda9',
    storageBucket: 'petguardpro-efda9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYOut4ESr0TU80GyH1n995i4ujCmNRl_Y',
    appId: '1:751087584610:ios:2ca56db16ce96ea1b3d83b',
    messagingSenderId: '751087584610',
    projectId: 'petguardpro-efda9',
    storageBucket: 'petguardpro-efda9.firebasestorage.app',
    iosBundleId: 'com.example.smartPetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYOut4ESr0TU80GyH1n995i4ujCmNRl_Y',
    appId: '1:751087584610:ios:2ca56db16ce96ea1b3d83b',
    messagingSenderId: '751087584610',
    projectId: 'petguardpro-efda9',
    storageBucket: 'petguardpro-efda9.firebasestorage.app',
    iosBundleId: 'com.example.smartPetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP8pn5wR-tXM5fTe2eBAb-EJqjxBCZrno',
    appId: '1:751087584610:web:053a697f8546582cb3d83b',
    messagingSenderId: '751087584610',
    projectId: 'petguardpro-efda9',
    authDomain: 'petguardpro-efda9.firebaseapp.com',
    storageBucket: 'petguardpro-efda9.firebasestorage.app',
  );
}
